
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 29 18:20:51 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 45;
  public static final int CONST = 5;
  public static final int OP_GREATER = 29;
  public static final int OP_AND = 33;
  public static final int CONTINUE = 21;
  public static final int NUM_CONST = 43;
  public static final int FOR = 19;
  public static final int OP_INC = 35;
  public static final int OP_DIV = 25;
  public static final int OP_LPAREN = 2;
  public static final int OP_DOT = 37;
  public static final int CLASS = 10;
  public static final int OP_LESS_EQUAL = 32;
  public static final int OP_NOT_EQUAL = 28;
  public static final int OP_RPAREN = 3;
  public static final int OP_MUL = 24;
  public static final int IF = 12;
  public static final int OP_MOD = 26;
  public static final int ABSTRACT = 14;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int OP_OR = 34;
  public static final int IDENT = 42;
  public static final int BREAK = 9;
  public static final int OP_ASSIGN = 8;
  public static final int VOID = 18;
  public static final int OP_GREATER_EQUAL = 30;
  public static final int OP_MINUS = 23;
  public static final int OP_SEMI = 6;
  public static final int OP_RSQUARE = 39;
  public static final int OP_LSQUARE = 38;
  public static final int ELSE = 11;
  public static final int OP_LESS = 31;
  public static final int READ = 16;
  public static final int OP_COMMA = 7;
  public static final int OP_DEC = 36;
  public static final int EXTENDS = 20;
  public static final int PROG = 4;
  public static final int OP_LBRACE = 40;
  public static final int BOOL_CONST = 44;
  public static final int OP_PLUS = 22;
  public static final int OP_EQUAL = 27;
  public static final int OP_RBRACE = 41;
  public static final int PRINT = 15;
}

