
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 25 23:25:49 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 4;
  public static final int CONST = 9;
  public static final int OP_GREATER = 36;
  public static final int OP_AND = 32;
  public static final int CONTINUE = 24;
  public static final int NUM_CONST = 3;
  public static final int FOR = 22;
  public static final int OP_INC = 29;
  public static final int OP_DIV = 43;
  public static final int OP_LPAREN = 18;
  public static final int OP_DOT = 34;
  public static final int CLASS = 16;
  public static final int OP_LESS_EQUAL = 39;
  public static final int OP_NOT_EQUAL = 35;
  public static final int OP_RPAREN = 19;
  public static final int OP_MUL = 42;
  public static final int IF = 21;
  public static final int OP_MOD = 44;
  public static final int ABSTRACT = 15;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int NEW = 41;
  public static final int error = 1;
  public static final int OP_OR = 31;
  public static final int BREAK = 23;
  public static final int IDENT = 2;
  public static final int OP_ASSIGN = 11;
  public static final int VOID = 20;
  public static final int OP_GREATER_EQUAL = 37;
  public static final int OP_MINUS = 33;
  public static final int OP_SEMI = 10;
  public static final int OP_LSQUARE = 13;
  public static final int OP_RSQUARE = 14;
  public static final int ELSE = 28;
  public static final int OP_LESS = 38;
  public static final int READ = 26;
  public static final int OP_COMMA = 12;
  public static final int OP_DEC = 30;
  public static final int EXTENDS = 17;
  public static final int PROG = 6;
  public static final int OP_LBRACE = 7;
  public static final int BOOL_CONST = 5;
  public static final int OP_PLUS = 45;
  public static final int OP_EQUAL = 40;
  public static final int OP_RBRACE = 8;
  public static final int PRINT = 27;
}

