
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 25 18:52:55 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_EQUAL = 8;
  public static final int ELSE = 17;
  public static final int IDENT = 15;
  public static final int OP_LBRACE = 3;
  public static final int OP_LPAREN = 6;
  public static final int RETURN = 9;
  public static final int NUM_CONST = 14;
  public static final int OP_PLUS = 10;
  public static final int IF = 16;
  public static final int OP_SEMI = 5;
  public static final int OP_COMMA = 11;
  public static final int EOF = 0;
  public static final int PROG = 2;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int VOID = 13;
  public static final int OP_RPAREN = 7;
  public static final int OP_RBRACE = 4;
}

