
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int BREAK = 3;
  public static final int CLASS = 4;
  public static final int ABSTRACT = 5;
  public static final int ELSE = 6;
  public static final int CONST = 7;
  public static final int IF = 8;
  public static final int NEW = 9;
  public static final int PRINT = 10;
  public static final int READ = 11;
  public static final int RETURN = 12;
  public static final int VOID = 13;
  public static final int FOR = 14;
  public static final int EXTENDS = 15;
  public static final int CONTINUE = 16;
  public static final int IDENT = 17;
  public static final int NUM_CONST = 18;
  public static final int CHAR_CONST = 19;
  public static final int BOOL_CONST = 20;
  public static final int OP_PLUS = 21;
  public static final int OP_MINUS = 22;
  public static final int OP_MUL = 23;
  public static final int OP_DIV = 24;
  public static final int OP_MOD = 25;
  public static final int OP_EQUAL = 26;
  public static final int OP_NOT_EQUAL = 27;
  public static final int OP_GREATER = 28;
  public static final int OP_GREATER_EQUAL = 29;
  public static final int OP_LESS = 30;
  public static final int OP_LESS_EQUAL = 31;
  public static final int OP_AND = 32;
  public static final int OP_OR = 33;
  public static final int OP_ASSIGN = 34;
  public static final int OP_INC = 35;
  public static final int OP_DEC = 36;
  public static final int OP_SEMI = 37;
  public static final int OP_COMMA = 38;
  public static final int OP_DOT = 39;
  public static final int OP_LPAREN = 40;
  public static final int OP_RPAREN = 41;
  public static final int OP_LSQUARE = 42;
  public static final int OP_RSQUARE = 43;
  public static final int OP_LBRACE = 44;
  public static final int OP_RBRACE = 45;
  
  
}

